apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: public.ecr.aws/n5i9c7k0/todo:latest
      ports:
        - containerPort: 8000
