apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: \public.ecr.aws/o6c0o7l6/todo:latest
      ports:
        - containerPort: 8000
