kind: Service
apiVersion: v1
metadata:
  name: node-app-service
  namespace: node-app
spec:
  selector:
    app: node-app
    # must match the pod label
  ports:
    - protocol: TCP
      port: 8000 # service port
      targetPort: 8000 # container port 
